---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/LOI_survey2/LOI_survey2.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/15752/articles/17638/master/file/figures/LOI_survey2/LOI_survey2.png"
